name: 'test run'
description: 'test of docker on gh actions'
inputs:
  file:
    description: 'file of town names to render'
    required: true
    default: '/build/towns.txt'
outputs:
  time:
    description: 'time of run'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file }}
