name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup build
      uses: docker/setup-buildx-action@v1

    - name: Build
      uses: docker/build-push-action@v2
      id: docker_build
      with:
        tags: towns
        push: false

    - name: Run entrypoint
      uses: addnab/docker-run-action@v3
      with:
        image: towns
        run: |
         sh ./entrypoint.sh towns.txt

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
