name: Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up buildx
      uses: docker/setup-buildx-action@v1

    - name: Build docker image
      run: docker build -t towns .
    
    - name: Run container
      run: |
        docker run --rm -v /data:/data -t towns /test.txt
      with:
        context: .
