name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: docker/build-push-action@v2
      with:
        tags: towns
        push: false

    - name: Run entrypoint
      uses: addnab/docker-run-action@v3
      with:
        image: towns
        run: |
          echo "test run"
