name: Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build 
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        tags: towns:latest
        push: false
        context: .
        load: true

    - name: Run script
      uses: kohlerdominik/docker-run-action@v1
      with:
        image: towns:latest
        run: pwd
